### ISSUE TITLE
Wii U Pro Controller Pairs but not recognized by Steam

### ISSUE THREAD

**Issue by chaz-clark** [WiiController/WiiController#15]
I can pair my Wii U Pro controller to my Mac running OS Catalina. When I open Steam and enable all the remote options, it does not recognize the controller as a paired device. I tested pairing with an 8bitdo USB and Steam recognizes the Wii U controller but is not able to sustain a connection. This somewhat shows that Steam should recognize it and can but is not. Am I missing a step to let steam see the Bluetooth-connected Wii U Pro controller?

**Comment by ThatsJustCheesy** [comment]
Hi, sorry for leaving this unanswered.

I've just tried with Steam in Big Picture mode. It picks up the controller fine for me, but the input is severely delayed, i.e., unusable. I'm not sure why.

Unfortunately, I don't have the resources or desire to properly work on Steam support right now. For the time being, I would recommend using the controller to [drive mouse and keyboard input](https://github.com/WiiController/WiiController/wiki/Driving-mouse-and-keyboard-input-with-Wii-controllers) if possible.

Let me know if you have any further questions, I'll try to answer sooner.

**Comment by chaz-clark** [comment]
I know this issue was closed. I removed and reinstalled the WiiController and that for what ever reason fixed my connection issue. It worked ok for navigating the Big Picture mode within Steam. I did find more success with the use of it to map mouse and keyboard movements and was able to play Minecraft. Thanks for the recommendation!

**Comment by ThatsJustCheesy** [comment]
Glad you got it working :)
