### ISSUE TITLE
WiiController not working on MacOS Monterey

### ISSUE THREAD

**Issue by NeilAgar** [WiiController/WiiController#17]
When launching the newest version of WiiController with SIP disabled and code signing in terminal, the WiiController menu that usually shows up at the top (as it did on previous MacOS versions) doesn't. 

No errors are present so I'm not sure what information I could give about this.

**Comment by ThatsJustCheesy** [comment]
Hi! This is a known issue. I will investigate as soon as I've upgraded to Monterey myself.

Please subscribe to issue #16 for further updates. Thanks for your patience!
