### ISSUE TITLE
(Not exactly related, nor and issue, kinda just a request)

### ISSUE THREAD

**Issue by Mox4572** [WiiController/WiiController#19]
Could you work on adding Switch controller support? With mapping to the OSes built in Gamepad support(I.e Xbox/Playstation controller inputs(Buttons))?

**Comment by ThatsJustCheesy** [comment]
As I understand it, the Switch controllers use a completely different protocol. It would be a fair amount of work and testing, and I don't own any Switch controllers at the moment.

Have you seen this app? (It doesn't do exactly what you asked, but maybe you could make it work?) https://apps.apple.com/ca/app/joykeymapper/id1511416593?mt=12

Sorry I can't be of further help.
