### ISSUE TITLE
Button assignments are suboptimal

### ISSUE THREAD

**Issue by ThatsJustCheesy** [WiiController/WiiController#2]
When using standard-ish-layout Wii controllers (Classic, U Pro), the button numbers assigned are… suboptimal. They should be changed to more typical values.

**Comment by ThatsJustCheesy** [comment]
Introduced device profiles for customizable button layout.

**Comment by HomeStarRunnerTron** [comment]
Oh my goodness, that's amazing! Has this change been publicly released, or should I just hang tight? This is going to be such a game changer, thank you so-so much for your continued efforts!

**Comment by ThatsJustCheesy** [comment]
Just released :)
