### ISSUE TITLE
Wii motion +

### ISSUE THREAD

**Issue by Pokeknight2610** [WiiController/WiiController#21]
You said to open an issue for it if I want it implemented, and here it is. I think i bricked my wii u and want to play wii sports resort with friends and stuff. Can you possibly set this up? I am more of a windows person but my parents only have a macbook, i believe its at the last version of 10 so this will work.

**Comment by HomeStarRunnerTron** [comment]
Hey-- so, if you have Wiimotes, try this, instead: https://github.com/dolphin-emu/WiimotePair
Install and open up Dolphin, after pairing through that program, and you should be in business running a ROM of Wii Sports Resort through Dolphin -- make sure controller settings are correct: https://dolphin-emu.org/

**Comment by Pokeknight2610** [comment]
Hmm. My mac is not running 12 or newer. I think its like 10.12 or 10.15 or smth

**Comment by HomeStarRunnerTron** [comment]
> Hmm. My mac is not running 12 or newer. I think its like 10.12 or 10.15 or smth

Oogh, options for running Wii games on Intel Macs ain't exactly the best. It's probably going to be too slow for your liking. Give it a shot, though.

HOWEVER, that means you can use the only release of WiiController, and it's going to work perfectly!

https://github.com/WiiController/WiiController/releases/tag/v0.14.0 <-- Just download this one and install it, open it, and sync your Wiimotes.

-- If the Wii emulation is too slow, your best bet is to run Windows through Boot Camp, and add custom drivers through https://www.bootcampdrivers.com/ .

(Oh, and if you DO use it on Windows, I think Touchmote's your best bet for using your Wiimotes: https://touchmote.net/ )

**Comment by Pokeknight2610** [comment]
Alright, I'll give it a shot. I got dolphin on there, which is ironic because parental controls didn't give a shit when I tried to install it, and dolphin is a very well-known emulator that I wouldn't expect to run on a 2010 MacBook pro. If this makes it better,  I am 100% for it.
